# ResNet50

python eval_ctsrbm_examples.py resnet_ret_train/test_50_000__eval_ctsrbm_examples.json resnet_ret_train/test_50_000__train_ret_DDP.json
python eval_ctsrbm_examples.py resnet_ret_train/test_50_001__eval_ctsrbm_examples.json resnet_ret_train/test_50_001__train_ret_DDP.json
python eval_ctsrbm_examples.py resnet_ret_train/test_50_002__eval_ctsrbm_examples.json resnet_ret_train/test_50_002__train_ret_DDP.json
python eval_ctsrbm_examples.py resnet_ret_train/test_50_003__eval_ctsrbm_examples.json resnet_ret_train/test_50_003__train_ret_DDP.json
python eval_ctsrbm_examples.py resnet_ret_train/test_50_004__eval_ctsrbm_examples.json resnet_ret_train/test_50_004__train_ret_DDP.json
python eval_ctsrbm_examples.py resnet_ret_train/test_50_005__eval_ctsrbm_examples.json resnet_ret_train/test_50_005__train_ret_DDP.json
python eval_ctsrbm_examples.py resnet_ret_train/test_50_006__eval_ctsrbm_examples.json resnet_ret_train/test_50_006__train_ret_DDP.json
python eval_ctsrbm_examples.py resnet_ret_train/test_50_007__eval_ctsrbm_examples.json resnet_ret_train/test_50_007__train_ret_DDP.json
python eval_ctsrbm_examples.py resnet_ret_train/test_50_008__eval_ctsrbm_examples.json resnet_ret_train/test_50_008__train_ret_DDP.json

# EfficientNetB3

python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_000__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_000__train_ret_DDP.json
python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_001__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_001__train_ret_DDP.json
python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_002__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_002__train_ret_DDP.json
python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_003__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_003__train_ret_DDP.json
python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_004__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_004__train_ret_DDP.json
python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_005__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_005__train_ret_DDP.json
python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_006__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_006__train_ret_DDP.json
python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_007__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_007__train_ret_DDP.json
python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_008__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_008__train_ret_DDP.json
python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_009__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_009__train_ret_DDP.json
python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_010__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_010__train_ret_DDP.json
python eval_ctsrbm_examples.py efficientnet_ret_train/test_b3_011__eval_ctsrbm_examples.json efficientnet_ret_train/test_b3_011__train_ret_DDP.json

# ConvNeXt-T

python eval_ctsrbm_examples.py convnext_ret_train/test_t_000__eval_ctsrbm_examples.json convnext_ret_train/test_t_000__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_001__eval_ctsrbm_examples.json convnext_ret_train/test_t_001__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_002__eval_ctsrbm_examples.json convnext_ret_train/test_t_002__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_003__eval_ctsrbm_examples.json convnext_ret_train/test_t_003__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_004__eval_ctsrbm_examples.json convnext_ret_train/test_t_004__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_005__eval_ctsrbm_examples.json convnext_ret_train/test_t_005__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_006__eval_ctsrbm_examples.json convnext_ret_train/test_t_006__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_007__eval_ctsrbm_examples.json convnext_ret_train/test_t_007__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_008__eval_ctsrbm_examples.json convnext_ret_train/test_t_008__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_009__eval_ctsrbm_examples.json convnext_ret_train/test_t_009__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_010__eval_ctsrbm_examples.json convnext_ret_train/test_t_010__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_011__eval_ctsrbm_examples.json convnext_ret_train/test_t_011__train_ret_DDP.json
python eval_ctsrbm_examples.py convnext_ret_train/test_t_012__eval_ctsrbm_examples.json convnext_ret_train/test_t_012__train_ret_DDP.json
